name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: felipemenegueli
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        with:
          author_name: snake-bot
          author_email: snake-bot@users.noreply.github.com
          message: "Generate contribution snake"
          add: "dist/github-contribution-grid-snake.svg"
